# BLANK CONFIG
[discord]
token = ''
discord_client_id = ''
discord_client_secret = ''

[dev]
host_internal_servers = false

[osu]
token = ''

[youtube]
api_key = ''
app_name = ''
callback_address = 'http://public_path_to_server'
callback_port = 8001
signing_key = 'any_secret_string'
internal_video_api_port = 8010

[postgres]
connection_string = 'jdbc:postgresql://127.0.0.1/database?user=username&password=password'

[mongoDB]
address = '127.0.0.1'
port = 27017
username = ''
password = ''
auth_db = 'kizunaai'
bot_db = 'kizunaai'

[netty]
port = 8000
domain = 'http://public_path_to_server'

[twitch]
client_id = ''
client_secret = ''
app_access_token = ''
twitch_callback_url = 'https://'
twitch_callpath_path = '/twitch'
twitch_callback_internal_port = 8003 # Twitch requires :443, must reroute to this internal port
twitch_signing_key = ''

[censor]
ip_services = [
    'http://checkip.amazonaws.com'
]

[admin]
admin_user = [
    83452231084412928
]
admin_channels = [
    582802415057633281
]
admin_guilds = [
    314662502204047361,
    581785820156002304
]
log_channel = 0

[twitter]
api_key = ''
api_key_secret = ''
bearer_token = ''

[microsoft]
translator_key = ''

[google]
gtranslator_key = ''
feed_inclusion_list = [
	0
]

[argos]
lt_address = '127.0.0.1:5000'

[ps2]
census_id = ''

[twitcasting]
twitcast_client_id = ''
twitcast_client_secret = ''
twitcast_webhook_port = 8002
twitcast_webhook_signature = ''

[deepl]
deepl_key = ''

[wolfram]
wolfram_appid = ''

[oauth]
root_oauth_uri = ''
port_block_start = ''
oauth_signing_key = ''

[mal]
mal_client_id = ''